ACCOUNTS=[
"GB7LDZXOU33YHDCCHOI45SEJYF4RC2E6WDK2UDEMDHYL57GWDP424ROM",
"GDSBRSL7K5CW7LA3K4NDCAYIHSCKLPMKYKXH2XEHRNQ5H32S67CUOZSS",
"GCJY52U5SC6VPN772PPSHBHTXBVGA4FLQ4ZBPGTFBIWC22NPQJKZZOMA",
"GAGL4YIU6RMAIDMGOFGPIOVPYVOPUTJSU7ZPA4DZ5SYJQSXX5VB6PD3R",
"GC6SBLAU6LSAZIYIX7OANAENRPDJW44V2S56H5BH2UUYSLYYLRIOAW3K",
"GCABSWN6GWNGS3Y3KBL3DEQN5H5G45BGBUUJ7ZZVUJBNPJR24FPXHE7D",
"GDXZ2HWUEWGYMTEPQRU6BUM6NQLCERWAWHAY5I5D5CGJ7UGH6BXI5S66",
"GBM7BHEWFN66Y7QDCWWO2JIM4BGIHO4VD5Z3XJESGITM6PGJVVHNJ3W7"
]

[DOCUMENTATION]
ORG_NAME="Monetary and fiscal research & development initiative"
ORG_DBA="MFRDI"
ORG_URL="https://mfrdi.go4io.com"
ORG_DESCRIPTION="mfrdi"
ORG_OFFICIAL_EMAIL=""

[[PRINCIPALS]]
name=""
email=""

# asset with meta info
[[CURRENCIES]]
code="XRTCN"
issuer="GB7LDZXOU33YHDCCHOI45SEJYF4RC2E6WDK2UDEMDHYL57GWDP424ROM"
display_decimals=7
name="XRTCN"
desc=""

[[CURRENCIES]]
code="DNR"
issuer="GCJY52U5SC6VPN772PPSHBHTXBVGA4FLQ4ZBPGTFBIWC22NPQJKZZOMA"
display_decimals=7
name="DNR"
desc="Every DNR is equivalent with 3.9 grams of real physical gold. The purity of this DNR-gold is 999 Finegold or 24 carat."
conditions="1 DNR corresponds to 3.9 grams of real 999 finegold."
is_asset_anchored=true
regulated=true
anchor_asset="GOLD"
image="https://mfrdi.go4io.com/.well-known/DNR_Logo.png"

[[CURRENCIES]]
code="XKCN"
issuer="GC6SBLAU6LSAZIYIX7OANAENRPDJW44V2S56H5BH2UUYSLYYLRIOAW3K"
display_decimals=7
name="XKCN"
desc=""

[[CURRENCIES]]
code="RMCN"
issuer="GDXZ2HWUEWGYMTEPQRU6BUM6NQLCERWAWHAY5I5D5CGJ7UGH6BXI5S66"
display_decimals=7
name="RMCN"
desc=""

# optional extra information for humans

###################################
# 
#
#
#
#
#
#
#
#
#